spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: Nguyenanh_96

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    oauth2:
      client:
        registration:

          facebook:
            clientId: 2165901433519390
            clientSecret: 68d8a95766bae331d53c5b1672e15a1e
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile

        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.3/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.3/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.3/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
app:
  auth:
    tokenSecret: nguyenanh240696
    tokenExpirationMsec: 864000000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the frontend client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:4200/oauth2/redirect


#
## database configurations
#spring.datasource.url=jdbc:mysql://localhost:3306/test?useSSL=false
#spring.datasource.username=root
#spring.datasource.password=Nguyenanh_96
#spring.jpa.generate-ddl=true
##Oauth2
#spring.security.oauth2.client.registration.facebook.client-id=2165901433519390
#spring.security.oauth2.client.registration.facebook.client-secret=68d8a95766bae331d53c5b1672e15a1e
#spring.security.oauth2.client.registration.facebook.redirect-uri="{baseUrl}/oauth2/callback/{registrationId}"
#spring.security.oauth2.client.registration.facebook.scope.=email, public profile
#spring.security.oauth2.client.provider.facebook.authorization-uri=https://www.facebook.com/v3.0/dialog/oauth
#spring.security.oauth2.client.provider.facebook.token-uri=https://graph.facebook.com/v3.0/oauth/access_token
##spring.security.oauth2.client.provider.facebook.user-info-uri=https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
## hibernate configurations
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialet=org.hibernate.dialect.MySQL5Dialect
## upload file
#spring.servlet.multipart.enabled=true
#spring.servlet.multipart.max-file-size=200MB
#spring.servlet.multipart.max-request-size=200MB
#path.file-upload=/home/nguyenanh/Desktop/Back-end-story/src/main/resources/upload-dir/
##app
#app.auth.tokenSecret=nguyenanh240696
#app.auth.tokenExpirationMsec=864000000
#app.oauth2.authorizedRedirectUris=http://localhost:4200/oauth2/redirect